name: Build uncloud for Debian

on:
  workflow_dispatch:
    inputs:
      uncloud_version:
        description: The version of uncloud to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true

permissions:
  contents: write

jobs:
  build-uncloud:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout uncloud-debian
        uses: actions/checkout@v4

      - name: Build uncloud
        run: ./build.sh ${{ inputs.uncloud_version }} ${{ inputs.build_version }}
      
      - name: Upload uncloud Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: | 
            uncloud_*.deb
            docker-pussh_*.deb 


  release-uncloud:
    name: (Draft-)Release uncloud for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-uncloud
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            uncloud_*.deb
            docker-pussh_*.deb
          name: ${{ inputs.uncloud_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
